name = "xdg_base_dir"
description = "XDG Base Directory Specification"
version = "1.0.0"
website = "https://github.com/onox/xdg-base-dir"
licenses = "Apache-2.0"
tags = ["xdg"]

authors = ["onox"]
maintainers = ["onox <denkpadje@gmail.com>"]
maintainers-logins = ["onox"]

[available.'case(os)']
'windows' = false
'...' = true

[build-switches]
validation.compile_checks = "warnings"
"*".style_checks = ["-gnatygAOM99-Is"]
